version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - 5432:5432
  server:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASS=postgres_password
      - PG_DB=postgres
    ports:
      - 9000:9000
